# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Parking Pal' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Parking Pal

  target 'Parking PalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Parking PalUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  source 'https://github.com/CocoaPods/Specs.git'
    pod 'GoogleMaps'

end
